FROM node:18.16.0-alpine as builder
WORKDIR /web
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM byjg/nginx-extras:latest
COPY --from=builder /web/dist /usr/share/nginx/html
COPY --from=builder /web/start-nginx.sh /start.sh
COPY --from=builder /web/nginx.conf /etc/nginx/conf.d/nginx.conf.template
RUN chmod +x /start.sh
CMD /start.sh
