version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: ./dockerfile.prd
    container_name: dp-docker
    image: deep-feels-prd:latest
    ports:
      - 80:80
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
    networks:
      - deep-feels-api_default
networks:
  deep-feels-api_default:
    external: true
