version: '3'
services:
  web :
    build:
      context: ./
      dockerfile: ./dockerfile.dev
    container_name: dp-docker-dev
    image: deep-feels-dev:latest
    volumes:
     - /web/node_modules
     - ./:/web
    ports:
      - 3090:3090
    tty: true
