version: '3'
services:
  web :
    build:
      context: ./
      dockerfile: ./dockerfile.dev
    container_name: dp-docker-dev
    image: deep-feels-dev:latest
    volumes:
     - ./:/web
     - /web/node_modules
    ports:
      - 3090:3090
    tty: true
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
    networks:
      - deep-feels-api_default
networks:
  deep-feels-api_default:
    external: true
