name: Deploying application

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      -
        name: Build and push
        run: |
          docker-compose -f ./docker.compose.prd.yml build
          docker tag deep-feels-prd:latest ${{ secrets.DOCKERHUB_USERNAME }}/deep-feels-prd:${{github.sha}}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/deep-feels-prd:${{github.sha}}
      -
        name: Deploy image to PRD
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PRD_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            docker rm -f $(docker ps -aq)
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/deep-feels-prd:${{github.sha}}
            docker run -d -p 80:${{ secrets.CONTAINER_PORT }} ${{ secrets.DOCKERHUB_USERNAME }}/deep-feels-prd:${{github.sha}}
          
