name: Deploying application

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      -
        name: Build and push
        run: |
          docker-compose -f ../../docker.compose.prd.yml build
          docker tag deep-feels-prd:latest ${{ secrets.DOCKERHUB_USERNAME }}/deep-feels-prd:${{github.sha}}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/deep-feels-prd:${{github.sha}}
          
